name: sistema_tatuajes
description: Sistema de Gestión de Tatuajes con Flutter y SQLite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Base de datos
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  path_provider_windows: ^2.2.1
  path: ^1.8.3
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1

   # Gráficas
  fl_chart: ^0.66.0

   # Calendario
  table_calendar: ^3.0.9
  
  # Utilidades
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  windows: 
    generate: true
    icon_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos: 
    generate: true
    icon_path: "assets/icon/app_icon.png"
    icon_size: 16

flutter:
  uses-material-design: true